/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardEncroachmentRouteImport } from './routes/dashboard.encroachment'
import { Route as DashboardExtractionRouteImport } from './routes/dashboard.extraction'
import { Route as DashboardGnssRouteImport } from './routes/dashboard.gnss'
import { Route as DashboardLandUseRouteImport } from './routes/dashboard.land-use'
import { Route as DashboardMapRouteImport } from './routes/dashboard.map'
import { Route as DashboardRolesRouteImport } from './routes/dashboard.roles'
import { Route as DashboardUploadRouteImport } from './routes/dashboard.upload'
import { Route as DashboardValidationRouteImport } from './routes/dashboard.validation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEncroachmentRoute = DashboardEncroachmentRouteImport.update({
  id: '/encroachment',
  path: '/encroachment',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExtractionRoute = DashboardExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGnssRoute = DashboardGnssRouteImport.update({
  id: '/gnss',
  path: '/gnss',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLandUseRoute = DashboardLandUseRouteImport.update({
  id: '/land-use',
  path: '/land-use',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardValidationRoute = DashboardValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/encroachment': typeof DashboardEncroachmentRoute
  '/dashboard/extraction': typeof DashboardExtractionRoute
  '/dashboard/gnss': typeof DashboardGnssRoute
  '/dashboard/land-use': typeof DashboardLandUseRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/validation': typeof DashboardValidationRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/encroachment': typeof DashboardEncroachmentRoute
  '/dashboard/extraction': typeof DashboardExtractionRoute
  '/dashboard/gnss': typeof DashboardGnssRoute
  '/dashboard/land-use': typeof DashboardLandUseRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/validation': typeof DashboardValidationRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/encroachment': typeof DashboardEncroachmentRoute
  '/dashboard/extraction': typeof DashboardExtractionRoute
  '/dashboard/gnss': typeof DashboardGnssRoute
  '/dashboard/land-use': typeof DashboardLandUseRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/validation': typeof DashboardValidationRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/encroachment'
    | '/dashboard/extraction'
    | '/dashboard/gnss'
    | '/dashboard/land-use'
    | '/dashboard/map'
    | '/dashboard/roles'
    | '/dashboard/upload'
    | '/dashboard/validation'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/analytics'
    | '/dashboard/encroachment'
    | '/dashboard/extraction'
    | '/dashboard/gnss'
    | '/dashboard/land-use'
    | '/dashboard/map'
    | '/dashboard/roles'
    | '/dashboard/upload'
    | '/dashboard/validation'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/encroachment'
    | '/dashboard/extraction'
    | '/dashboard/gnss'
    | '/dashboard/land-use'
    | '/dashboard/map'
    | '/dashboard/roles'
    | '/dashboard/upload'
    | '/dashboard/validation'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/encroachment': {
      id: '/dashboard/encroachment'
      path: '/encroachment'
      fullPath: '/dashboard/encroachment'
      preLoaderRoute: typeof DashboardEncroachmentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/extraction': {
      id: '/dashboard/extraction'
      path: '/extraction'
      fullPath: '/dashboard/extraction'
      preLoaderRoute: typeof DashboardExtractionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gnss': {
      id: '/dashboard/gnss'
      path: '/gnss'
      fullPath: '/dashboard/gnss'
      preLoaderRoute: typeof DashboardGnssRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/land-use': {
      id: '/dashboard/land-use'
      path: '/land-use'
      fullPath: '/dashboard/land-use'
      preLoaderRoute: typeof DashboardLandUseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/validation': {
      id: '/dashboard/validation'
      path: '/validation'
      fullPath: '/dashboard/validation'
      preLoaderRoute: typeof DashboardValidationRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardEncroachmentRoute: typeof DashboardEncroachmentRoute
  DashboardExtractionRoute: typeof DashboardExtractionRoute
  DashboardGnssRoute: typeof DashboardGnssRoute
  DashboardLandUseRoute: typeof DashboardLandUseRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardValidationRoute: typeof DashboardValidationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardEncroachmentRoute: DashboardEncroachmentRoute,
  DashboardExtractionRoute: DashboardExtractionRoute,
  DashboardGnssRoute: DashboardGnssRoute,
  DashboardLandUseRoute: DashboardLandUseRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardValidationRoute: DashboardValidationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
